
email: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
domain: ""

exclude: [src, node_modules, package*, Gemfile*]

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

# Site navigation - each item must have a label and a url.
navigation:
  - en: team
    cy: tîm
    url: /team/
  - en: updates
    cy: diweddariadau
    url: /updates/

# Colours
theme_color: '#326A85'
accent_color: '#326A85'
text_color: '#0A0908'
secondary_text_color: '#20201D'
link_color: '#3E81A3'
background_color: '#fbfbfb'
page_color: '#ffffff'
border_color: '#d7d7d7'

t:
  en:
    title: Site title
    description: "Describe your site"
    language: English
    root: /en
    welcome: Welcome to
    team: team
    by: by
    share: share
  cy:
    title: Teitl y safle
    description: "Disgrifiwch eich gwefan"
    language: Cymraeg
    root: /cy
    welcome: Croeso i
    team: tîm
    by: gan
    share: rhannu

