
email: ""
baseurl: "/week-notes" # the subpath of your site, e.g. /blog
url: "https://nrw-digital.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
domain: ""

exclude: [src, node_modules, package*, Gemfile*]

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

# Site navigation - each item must have a label and a url.
navigation:
  - en: team
    cy: tîm
    url: /team/
  - en: updates
    cy: diweddariadau
    url: /updates/

# Colours
theme_color: '#008393'
accent_color: '#326A85'
text_color: '#0A0908'
secondary_text_color: '#20201D'
link_color: '#007485'
background_color: '#fbfbfb'
page_color: '#ffffff'
border_color: '#d7d7d7'

t:
  en:
    title: Natural Resources Wales week notes
    description: "Describe your site"
    language: English
    root: /week-notes/en
    welcome: Welcome to
    team: team
    by: by
    share: share
    top : top
    toptext: go to the top of the page
    contact : contact us
    nrw : NRW
    power : powered by
    menu: menu
    skip: Skip To Main Content
    openmenu: open menu
  cy:
    title: Cyfoeth Naturiol Cymru nodiadau wythnos
    description: "Disgrifiwch eich gwefan"
    language: Cymraeg
    root: /week-notes/cy
    welcome: Croeso i
    team: tîm
    by: gan
    share: rhannu
    top : i fyny
    toptext: ewch i frig y dudalen
    contact : cysylltu â ni
    nrw : CNC
    power : wedi ei bweru gan
    menu: bwydlen
    skip: Sgipio I’r Prif Gynnwys
    openmenu: dewislen agored